# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
default_install_hook_types: [pre-push, pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents] # for .clang-format
    -   id: check-added-large-files
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.5
    hooks:
    -   id: clang-format
-   repo: local
    hooks:
    -   id: clang-tidy-diff
        name: clang-tidy-diff
        entry: tools/tidy -quiet
        pass_filenames: false
        language: system
        stages: ["pre-push"]
